name: car_admin
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  get: ^4.6.5
  cached_network_image: ^3.2.1
  smooth_page_indicator: ^1.0.0+2
  get_storage: ^2.0.3
  flutter_colorpicker: ^1.0.3
  image_picker: ^0.8.5+3
  file_picker: ^4.5.1
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0



flutter:

 
  uses-material-design: true
  assets:
    - assets/images/
  